from __future__ import annotations

from constructor_agent.domain import AgentState, EndpointSpec


class PromptFactory:
    """Creates prompts for the endpoint chain."""

    def build_endpoint_prompt(self, endpoint: EndpointSpec, state: AgentState) -> str:
        current_answer = state.get("current_answer")
        if not current_answer:
            return self._initial_prompt(endpoint, state["original_query"])
        return self._revision_prompt(
            endpoint=endpoint,
            original_query=state["original_query"],
            previous_endpoint=state.get("current_endpoint_id") or "unknown",
            previous_answer=current_answer,
        )

    @staticmethod
    def _initial_prompt(endpoint: EndpointSpec, original_query: str) -> str:
        return f"""You are an LLM endpoint in a sequential agentic system.

Endpoint id: {endpoint.id}
Endpoint role: {endpoint.role}
Endpoint description: {endpoint.description}

Original user query:
{original_query}

Task:
Produce the first answer to the original user query.
The answer must be precise, operational, and explicit.
Return only the answer.
"""

    @staticmethod
    def _revision_prompt(
        endpoint: EndpointSpec,
        original_query: str,
        previous_endpoint: str,
        previous_answer: str,
    ) -> str:
        return f"""You are an LLM endpoint in a sequential agentic review system.

Endpoint id: {endpoint.id}
Endpoint role: {endpoint.role}
Endpoint description: {endpoint.description}

Original user query:
{original_query}

Previous endpoint:
{previous_endpoint}

Previous answer:
{previous_answer}

Task:
1. Check whether the previous answer is correct, complete, and useful.
2. Identify errors, omissions, unclear parts, and unsupported statements.
3. Improve the answer.
4. Preserve all correct and useful content.
5. Return a complete improved answer, not just comments.

Return only the improved answer.
"""

    @staticmethod
    def build_final_explanation(state: AgentState) -> str:
        exchanges = state.get("exchanges", [])
        lines = [
            "The answer was produced by a LangGraph state machine built from the XML configuration.",
            f"The graph executed {len(exchanges)} endpoint step(s).",
            "",
            "Execution path:",
        ]
        for i, exchange in enumerate(exchanges, start=1):
            lines.append(
                f"{i}. endpoint={exchange.endpoint_id}; "
                f"llm_alias={exchange.llm_alias}; "
                f"mode={exchange.mode}; role={exchange.role}"
            )
        lines.append("")
        lines.append(
            "Each step received the original query. Every step after the first also received "
            "the answer produced by the preceding endpoint and was asked to judge whether it "
            "was acceptable and how it should be improved. The returned answer is the last "
            "answer generated by the configured path."
        )
        return "\n".join(lines)
