from __future__ import annotations

from constructor_agent.domain import AgentState, QuestionSpec


class PromptFactory:
    """Creates prompts for the question chain."""

    def build_question_prompt(self, question: QuestionSpec, state: AgentState) -> str:
        current_answer = state.get("current_answer")

        if question.prompt:
            return self._custom_prompt(question, state)

        if not current_answer:
            return self._initial_prompt(question, state["original_prompt"])

        return self._revision_prompt(
            question=question,
            original_prompt=state["original_prompt"],
            previous_question=state.get("current_question_id") or "unknown",
            previous_answer=current_answer,
        )

    @staticmethod
    def _custom_prompt(question: QuestionSpec, state: AgentState) -> str:
        original_prompt = state["original_prompt"]
        current_answer = state.get("current_answer") or ""

        replacements = {
            "prompt": original_prompt,
            "answer": current_answer,
            "input": current_answer if current_answer else original_prompt,
            "original_prompt": original_prompt,
            "previous_answer": current_answer,
            "previous_question": state.get("current_question_id") or "unknown",
            "question_id": question.id,
            "question_role": question.role,
            "question_description": question.description,
        }

        for exchange in state.get("exchanges", []):
            replacements[f"{exchange.question_id}.prompt"] = exchange.prompt
            replacements[f"{exchange.question_id}.answer"] = exchange.answer

        return PromptFactory._replace_placeholders(
            question.prompt or "",
            replacements,
        )

    @staticmethod
    def _replace_placeholders(template: str, replacements: dict[str, str]) -> str:
        result = template

        for key in sorted(replacements.keys(), key=len, reverse=True):
            result = result.replace("{" + key + "}", replacements[key])

        return result

    @staticmethod
    def _initial_prompt(question: QuestionSpec, original_prompt: str) -> str:
        return f"""You are an LLM question step in a sequential agentic system.

Question id: {question.id}
Question role: {question.role}
Question description: {question.description}

Original user prompt:
{original_prompt}

Task:
Produce the first answer to the original user prompt.
The answer must be precise, operational, and explicit.
Return only the answer.
"""

    @staticmethod
    def _revision_prompt(
        question: QuestionSpec,
        original_prompt: str,
        previous_question: str,
        previous_answer: str,
    ) -> str:
        return f"""You are an LLM question step in a sequential agentic review system.

Question id: {question.id}
Question role: {question.role}
Question description: {question.description}

Original user prompt:
{original_prompt}

Previous question:
{previous_question}

Previous answer:
{previous_answer}

Task:
1. Check whether the previous answer is correct, complete, and useful.
2. Identify errors, omissions, unclear parts, and unsupported statements.
3. Improve the answer.
4. Preserve all correct and useful content.
5. Return a complete improved answer, not just comments.

Return only the improved answer.
"""

    @staticmethod
    def build_final_explanation(state: AgentState) -> str:
        exchanges = state.get("exchanges", [])

        lines = [
            "The answer was produced by a LangGraph state machine built from the XML configuration.",
            f"The graph executed {len(exchanges)} question step(s).",
            "",
            "Execution path:",
        ]

        for i, exchange in enumerate(exchanges, start=1):
            lines.append(
                f"{i}. question={exchange.question_id}; "
                f"llm_alias={exchange.llm_alias}; "
                f"mode={exchange.mode}; role={exchange.role}"
            )

        lines.append("")
        lines.append(
            "Each question step received the original prompt. Every step after the first "
            "also received the answer produced by the preceding step. The returned answer "
            "is the last answer generated by the configured path."
        )

        return "\n".join(lines)